[downloader]
year = 2023
taxi_type = "green"
dir_dataset = "dataset_ny_taxi"

[trainer]
month = 0
train_year = 2021
test_year = 2024
taxi_type = "green"
dir_dataset = "dataset_ny_taxi"
regressor_type = "linear"
# for local
mlflow_tracking_uri = "sqlite:///mlruns.db"
# for AWS, replace PUBLIC_DNS in the below link
# mlflow_tracking_uri = http://PUBLIC_DNS:5000
experiment_name = "ny_taxi"
