[batch_deployment]
month = 1
year = 2024
taxi_type = "green"
model_for_inference = "./model_for_prod"
dir_dataset = "../dataset_ny_taxi"
# for AWS S3 bucket
dir_target = "s3://ny-taxi-ride-duration-prediction-results-abhi"
# dir_target = "../output"