name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    # skip tests since it will fail in GitHub actions since the model files are not added to the repo
    #- name: Test with pytest
    #  run: |
    #    make test
    - name: Format code
      run: |
        make format
    
